### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sharkyy27896** [Tophness/ChatGPT_PC_Controller#3]
I have no idea how to use python except for what I learned from this. I am getting this whenever I try to start it, how do I fix it?

C:\Users\mrdab\ChatGPT-PC-Controller>python main.py
Enter a task: notepad
Downloading chrome..
Download succeeded.
Enter your email: *********
Enter your password: *********
C:\Users\mrdab\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py:328: UserWarning: using ChromeOptions.user_data_dir might stop working in future versions.use uc.Chrome(user_data_dir='/xyz/some/data') in case you need existing profile folder
  warnings.warn(
could not detect version_main.therefore, we are assuming it is chrome 108 or higher
Traceback (most recent call last):
  File "C:\Users\mrdab\ChatGPT-PC-Controller\main.py", line 171, in <module>
    getCmd(OpenAIChat(), cmd_string)
  File "C:\Users\mrdab\ChatGPT-PC-Controller\main.py", line 142, in getCmd
    chatResult = chat.start(preprompt + " " + prompt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrdab\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAPIGrabber\chat\chat.py", line 348, in start
    self.login()
  File "C:\Users\mrdab\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAPIGrabber\chat\chat.py", line 339, in login
    self.access_token, self.cookie = chatToken.login()
                                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\mrdab\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenAIAPIGrabber\loader\loader.py", line 74, in login
    email_input = WebDriverWait(self.driver, 60).until(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrdab\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00F7A813+48355]
        (No symbol) [0x00F0C4B1]
        (No symbol) [0x00E15358]
        (No symbol) [0x00E409A5]
        (No symbol) [0x00E40B3B]
        (No symbol) [0x00E6E232]
        (No symbol) [0x00E5A784]
        (No symbol) [0x00E6C922]
        (No symbol) [0x00E5A536]
        (No symbol) [0x00E382DC]
        (No symbol) [0x00E393DD]
        GetHandleVerifier [0x011DAABD+2539405]
        GetHandleVerifier [0x0121A78F+2800735]
        GetHandleVerifier [0x0121456C+2775612]
        GetHandleVerifier [0x010051E0+616112]
        (No symbol) [0x00F15F8C]
        (No symbol) [0x00F12328]
        (No symbol) [0x00F1240B]
        (No symbol) [0x00F04FF7]
        BaseThreadInitThunk [0x75607BA9+25]
        RtlInitializeExceptionChain [0x778DC10B+107]
        RtlClearBits [0x778DC08F+191]
C:\Users\mrdab\ChatGPT-PC-Controller>

**Comment by Logani06** [comment]
Same for me

**Comment by Tophness** [comment]
Yeah sorry, this doesn't work anymore. It relied on the hidden API the original ChatGPT used.
In theory this should actually be easier now because you're supposed to be able to use the site without login cookies, but I have to start most of the code from scratch to make it work
